### ISSUE TITLE
Make tap strict mode optional

### ISSUE THREAD

**Issue by mcollina** [aghassemi/tap-xunit#3]
The library was working fine for us with the previous version, without `strict` tap mode.

Is it possible to make it optional? I can send a PR, but I would like to know if there was a particular reason to do so.

**Comment by aghassemi** [comment]
Hi @mcollina 

Made it optional and now it defaults to false. There was no good reason not to make it optional but I wanted to have strict mode so parser fails on bad TAP input. New change released under 1.2.1.
