### ISSUE TITLE
Ava tests piped through tap and then tap-xunit and then to temrinal?

### ISSUE THREAD

**Issue by atomless** [aghassemi/tap-xunit#9]
Hi, tap-xunit is working great for the purpose of Jenkins integration but I'd love to be able to have the output passed through so that I can have it both in xml *and* the terminal. Something like:
```
$ ava --tap | tap-xunit --file=foo.xml --passthrough | tap-spec
```
Would this be the kind of feature that could be added?

**Comment by aghassemi** [comment]
Hi @atomless 

You might be able to do this using `tee` command and a temp file, something like:

```
ava --tap | tee /tmp/ava.tap | tap-spec && cat /tmp/ava.tap | tap-xunit > ava.xml
```

**Comment by atomless** [comment]
I was just wrestling with tee but couldn't figure it out. Genius! Thanks!

**Comment by vkotovv** [comment]
@atomless what jenkins plugin do you use to process tap-xunit results?

**Comment by vkotovv** [comment]
Found the answer: you can use [Xunit plugin](https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin) with JUnit test result format
